baseURL: https://monique.dev/
defaultContentLanguage: pt-br
languageCode: pt-br
title: monique.dev

theme: LoveIt

#paginate: 5
#copyright: "MoniqueLive"
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true

author:
  name: Cyber

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

menu:
  main:
    - name: Arquivo
      url: /posts/
      identifier: archives
      weight: 10
    - name: Tags
      url: /tags/
      identifier: tags
      weight: 20
    - name: Categorias
      url: /categories/
      identifier: categories
      weight: 30
    - name: Sobre
      url: /about
      identifier: about
      weight: 999

languages:
  pt-br:
    params:
      home:
        profile:
          enable: true
          avatarURL: logo.jpg
          title: Monique.dev
          subtitle: Traduções das minhas postagens do site dev.to
          typeit: true
          social: true

params:
  version: 0.2.X
  defaultTheme: dark
  gitRepo: https://github.com/moniquelive/monique.dev
  dateFormat: "2006-01-02"

  app:
    title: Monique.dev
  search:
    enable: true
    type: lunr
  header:
    title:
      logo: /logo.jpg
      name: Monique.dev

  footer:
    hugo: true
    copyright: true
    author: true
    since: 2020
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  social:
    twitter: moniquelive
    github: moniquelive
    instagram: moniquelive.dev
    linkedin: moniquelive
    youtubechannel: UCML4uqYh36vkI0UTTGBxByg
    devto: moniquelive
    whatsapp: 5521982820415?text=%23mandaaudios&lang=pt_br
    RSS: true
    stackoverflow:
      id: 9793/cyber-oliveira
      Icon:
        Class: fab fa-stack-overflow fa-fw

  page:
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true

    comment:
      enable: true
      disqus:
        enable: true
        shortname: monique-dev

  analytics:
    enable: true
    google:
      id: UA-129884631-3
      anonymizeIP: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
