baseURL: https://monique.dev/
title: monique.dev
theme: coder
defaultContentLanguage: pt-br
languageCode: pt-br

paginate: 20

pygmentscodefences: true
pygmentscodefencesguesssyntax: true

disqusShortname: monique-dev
googleAnalytics: UA-129884631-3

enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

menu:
  main:
    - name: Blog
      url: /posts
      identifier: archives
      weight: 10
    - name: Tags
      url: /tags
      identifier: tags
      weight: 20
    - name: Sobre
      url: /about
      identifier: about
      weight: 999

params:
  author: moniquelive
  info: Traduções das minhas postagens do site dev.to
  avatarurl: /logo.jpg
  colorScheme: dark
  gitRepo: https://github.com/moniquelive/monique.dev
  dateFormat: "2006-01-02"
  enableTwemoji: true
  since: 2020
  footercontent: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  social:
    - name: twitter
      icon: fa fa-twitter fa-2x
      url: https://twitter.com/moniquelive
    - name: github
      icon: fa fa-github fa-2x
      url: https://github.com/moniquelive
    - name: instagram
      icon: fa fa-instagram fa-2x
      url: https://instagram.com/moniquelive.dev
    - name: linkedin
      icon: fa fa-linkedin fa-2x
      url: https://linkedin.com/in/moniquelive
    - name: youtube
      icon: fa fa-youtube fa-2x
      url: https://youtube.com/channel/UCML4uqYh36vkI0UTTGBxByg
#    - name: dev.to
#      icon: fab fa-dev fa-2x
#      url: https://devto.com/moniquelive
    - name: whatsapp
      icon: fa fa-whatsapp fa-2x
      url: https://wa.me/5521982820415?text=%23mandaaudios&lang=pt_br
    - name: stackoverflow
      icon: fa fa-stack-overflow fa-2x
      url: https://stackoverflow.com/users/9793/cyber-oliveira
    - name: rss
      icon: fa fa-rss fa-2x
      url: /index.xml

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
