baseURL: https://monique.dev/
title: monique.dev
theme: hugo-notepadium #m10c
copyright: "©2021 MoniqueLive."

languageCode: pt-br
defaultContentLanguage: pt-br

googleAnalytics: UA-129884631-3
disqusShortname: monique-dev
enableRobotsTXT: true

params:
  author: Cyber
  favicon: logo.jpg
  style: dark
  logo: logo.jpg
  slogan: Traduções das minhas postagens do site dev.to
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: Sobre
        url: /about
      - title: RSS
        url: /index.xml
  comments:
    enable: true

  profile:
    enable: true
    avatar: logo.jpg
    name: monique.dev
    bio: ""
    twitter: moniquelive
    github: lccro
    instagram: moniquelive.dev
    stack-overflow: https://stackoverflow.com/users/9793/cyber-oliveira
